### ISSUE TITLE
Wenn MS "Office Open XML" als textbasiert gilt, muss auch  das OpenDocument-Format als textbasiert gelten 

### ISSUE THREAD

**Issue by pietsch** [lzv-nrw/file-formats-table#1]
Wenn die neuen MS-Formate docx, xslx und pptx als Textformate gelten, denn müssen auch die OpenOffice-Formate odt, ods und odp als Textformate gelten.

Alle 6 genannten Formate sind in Wirklichkeit Zip-Dateien, die XML-Dateien und ggf. weitere Dateien enthalten.

Ich finde es OK, sie trotzdem als Textformate zu zählen, um den Fortschritt gegenüber den alten MS-Office-Formaten doc, xls und ppt zu würdigen, die durch und durch binär sind.

https://en.wikipedia.org/wiki/Office_Open_XML
https://en.wikipedia.org/wiki/OpenDocument

**Comment by KayhanOgan** [comment]
Die Dateiformattafel soll einen groben Überblick über langzeitstabile Dateiformate geben und als leichter Einstieg in die Thematik dienen. Daher sind einige technische Details mit Absicht simplifiziert dargestellt. Die genannten Beispiele .docx, .pptx usw. sind in der Tabelle dementsprechend als Dokumentenformate klassifiziert und filterbar, ohne auf ihren Aufbau genauer einzugehen. Die Gruppierung der Formate hat daher keinen Anspruch auf 100% Richtigkeit. 

Gerne können Sie die Tabelle auf einem eigenen Server entsprechend verändern, um eine feinere Einordnung der Dateiformate vorzunehmen.

**Comment by pietsch** [comment]
Sie haben meinen Hinweis missverstanden. Ich schlage keine Verkomplizierung vor, sondern eine konsistente Behandlung der Formate der verschiedenen Office-Suiten. Das wäre eine Korrektur und Vereinfachung.

**Comment by aquast** [comment]
Wir haben ganz explizit zwischen konventionellen Textformaten und den komplexeren Dokumentenformaten unterschieden, weil Dokumentformate, genau wie Sie schreiben, neben Text auch andere Inhaltselemente unterschiedlichster Form enthalten können. 

Neben reinen binär-Formaten hat sich dabei vor allem die Nutzung von Datei-Containern (zip etc..) mit einer Strukturdatei (XML) und ggf. weiteren assoziierten Dateien durchgesetzt. Insofern ähneln sich die Formate für Wordprocessing, Tabellenkalulation und Präsentationen funktional und von ihrer strukturellen Ausprägung untereinander stärker, als sie konventionellen Textdateien ähneln. Wir haben die Formate daher bewusst in Text- und Dokumentenformate getrennt (s. Screenshot).

![2023-03-20 13 21 16 www lzv nrw addd0e85175f](https://user-images.githubusercontent.com/3217145/226400964-b31b55f0-3032-4eaf-a1b2-1bf6b02e99f2.png)

**Comment by pietsch** [comment]
Auch Sie haben nicht verstanden, was ich geschrieben habe, also formuliere ich neu:

Das von neueren MS-Office-Versionen verwendete Format "Office Open XML" (Dateiendung endet auf x) ist ein Abklatsch des von OpenOffice/LibreOffice eingeführten Formats (Dateiendung beginnt mit o). In beiden Fällen handelt es sich um XML-Dateien in einem Zip-Container.

Wenn Sie MS "Office Open XML" als textbasiert bezeichnen, müssen Sie logischerweise auch das Format von OpenOffice/LibreOffice als textbasiert bezeichnen.

**Comment by hvwaldow** [comment]
@aquast : Nicht die filterbare Einteilung "Textformat" vs. "Dokumentformat" wird hier bemängelt. Die von @pietsch identifizierte Inkonsistenz bezieht sich auf die Klassifizierung "LZV Kriterien, Format", die mit 0/1 auf den Kacheln kodiert ist.

ODF und OOXML sind entweder beide bin, weil gezippt, oder beide text, weil xml.

**Comment by aquast** [comment]
@hvwaldow : Danke für die Erklärung. Leider hatten wir nicht verstanden, was @pietsch gemeint hat. Tatsächlich scheint es sich um eine Inkonsistenz zu handeln, die wir leicht beheben können.

Die Tabelle ist nicht unser vorrangiges Aufgabengebiet, insofern können wir nicht jederzeit sofort auf Korrekturen oder Verbesserungsvorschläge reagieren. Ein Pull-Request ist uns in diesem Sinne auch immer sehr willkommen :-)

**Comment by aquast** [comment]
PR #4 should solve the issue
