### ISSUE TITLE
Was ist die Bedeutung der Kacheln ASCII und XML?

### ISSUE THREAD

**Issue by rnuske** [lzv-nrw/file-formats-table#2]
Mir erschließt sich nicht was die Kacheln ASCII und XML symbolisieren sollen. 

In den zugehörigen Spalten stehen keine entsprechenden Dateiformate.

Sie passen nicht in die Tafel, da sie keine Dateiformate sind, und sie passen auch nicht zueinander, da das eine eine Zeichenkodierung und das andere eine Auszeichnungssprache ist.

**Comment by KayhanOgan** [comment]
Wir nehmen an dieser Stelle eine gewisse "künstlerische Freiheit" in Anspruch. ASCII ist die grundlegendste Kodierung für Texte. In einer chemischen Elementetabelle würde das dem Wasserstoff "H" entsprechen. XML entspricht dem Konzept eines "inerten" = "stabilen" Edelgases wie Helium, weil es ein textbasiertes Format ist, das zugleich Grundlage für Containerformate, Office-Formate etc. sein kann.

Wir möchten mit der Tabelle einen leichten und spielerischen Einstieg anbieten, weil wir nicht die gleichen Ressourcen für Formatevaluationen bereitstellen können, wie die zitierten sehr etablierten Projekte. Insofern haben wir keinen Anspruch auf 100%ige Ausdifferenzierung.
