### ISSUE TITLE
Was ist mit proprietär gemeint?

### ISSUE THREAD

**Issue by rnuske** [lzv-nrw/file-formats-table#3]
Mir ist unklar, was in diesem Zusammenhang mit proprietär gemeint ist.

Etliche der in der Tafel als frei gekennzeichneten Formate gelten als proprietär siehe [Wikipedia: Closed proprietary formats](https://en.wikipedia.org/wiki/Proprietary_file_format#Prominent_proprietary_formats) und andere wie docx und xlsx sind [ISO Standards](https://www.iso.org/committee/45374/x/catalogue/) (wenn auch umstritten in der Ausführung)

**Comment by KayhanOgan** [comment]
Mit proprietär sind hier vor allem Dateiformate gemeint, die sich im Besitz von Firmen befinden und daher in ihrer Nutzung und Langzeitstabilität eingeschränkt sind. Zum Beispiel weil die Dateiformatspezifikationen nicht öffentlich einsehbar sind und die Dateiformate nur von bestimmter, ggf. kommerzieller Software verwendet werden können. .docx fällt unter diese Definition und gilt daher nicht als langzeitstabiles Format, auch wenn es in der Nutzung weit verbreitet ist.

Unsere Einschätzung der Dateiformate basiert auf einem Abgleich von verschiedenen internationalen Quellen. Dazu gehören unter anderem KOST, die Library of Congress und die PRONOM-Datenbank der National Archives UK.

Anhand dieser Quellen haben wir versucht, den Empfehlungen der internationalen Community soweit wie möglich zu folgen. Dabei sind wir uns natürlich darüber bewusst, dass es je nach Anwendungsfall und Kriterien unterschiedliche Einschätzungen geben kann und individuell entschieden werden muss, welche Dateiformate sich tatsächlich eignen.
